stages:
  - docker_build_validate
  - docker_build_push

docker_build_validate:
  stage: docker_build_validate
  tags:
    - docker
  script:
    - git clone ${CI_REPOSITORY_URL}
    - export DOCKER_CLI_EXPERIMENTAL=enabled
    - docker buildx build -t ${CI_REGISTRY}/sysadmins/docker/docker-bounca --platform=linux/arm,linux/arm64,linux/amd64 .
  only:
    - merge_requests

docker_build_push:
  stage: docker_build_push
  tags:
    - docker
  script:
    - git clone ${CI_REPOSITORY_URL}
    - export DOCKER_CLI_EXPERIMENTAL=enabled
    - echo ${CI_REGISTRY_PASSWORD} | docker login ${CI_REGISTRY} -u ${CI_REGISTRY_USER} --password-stdin
    - docker buildx build -t ${CI_REGISTRY}/sysadmins/docker/docker-bounca:latest --platform=linux/arm,linux/arm64,linux/amd64 . --push
  only:
    refs:
      - master
